import "./globals.css";
import Navigation from "../../components/Navigation";
import "tailwindcss/tailwind.css";

export const metadata = {
  title: "My First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navigation />
        <main className="flex-grow container mx-auto p-4 md:p-10">
          {children}
        </main>
      </body>
    </html>
  );
}